default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  database: note_development
  username: ENV.fetch("POSTGRES_USER")
  password: ENV.fetch("postgres")
  port: 5432
  host: localhost