version: '3'
services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=note_development
    ports:
      - '5432:5432'
  queso:
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /app/backend
    ports:
      - "3000:3000"
    command: "rails s -b 0.0.0.0 -p 3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432
    networks:
      - proxynet
    depends_on:
      - db
#volumes:
#  db:
#    driver: local
networks:
  proxynet:
    driver: bridge
